apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      service: {{ .Release.Name }}
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}
        app: {{ .Release.Name }}
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: nginx:latest
          ports:
            - containerPort: 80
