apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      tier: {{ .Release.Name }}
      track: stable
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tier: {{ .Release.Name }}
        track: stable
    spec:
      containers:
        - name: {{ .Values.name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          image: {{ .Values.image }}
          ports:
            - name: {{ .Release.Name }}-port
              containerPort: {{ .Values.deployment.containerPort }}

